### ISSUE TITLE
theme toggle overlay bug

### ISSUE THREAD

**Issue by superbahbi** [superbahbi/YABA#41]
**Describe the bug**
Theme toggle overlay bug

**To Reproduce**
1. Go to the landing page
2. Check the top right toggle icon
3. See an error

**Expected behavior**
Checkbox should invisible

**Screenshots**
![download](https://user-images.githubusercontent.com/1689092/193464479-55399de2-ae3b-4794-8e28-22ef7cdfe439.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 105.0.5195.125 

**Additional context**
First experienced the bug when installing tailwind plugin @tailwindcss/forms

**Comment by IzMichael** [comment]
Could I claim this?

**Comment by superbahbi** [comment]
Yes, you can. Thanks @IzMichael

**Comment by IzMichael** [comment]
My PR (#52) fixes this
